name: Sync to Hugging Face
on:
  push:
    branches: [ "main" ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Git LFS
        run: git lfs install
      - name: Push to Hugging Face
        run: |
          git remote add hf https://huggingface.co/Oncesane/LTX-2-3-OSAS
          git push hf main
        env:
          HF_TOKEN: ${{ secrets.GIT_TOKEN }}
